services:
  db:
    image: postgres:16-alpine
    container_name: mindful_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mindful
    ports:
      - "5432:5432"
    volumes:
      - mindful_db_data:/var/lib/postgresql/data

volumes:
  mindful_db_data:
